name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Run tests
        run: npm ci && npm test
      - name: Release
        if: ${{ success() }}
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
